name: 创建 VNC + noVNC 爬虫镜像

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.cron'
      - 'start-cron.sh'
      - 'package-cron.json'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # 添加这一行    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.cron
          push: true
          tags: |
            ghcr.io/rickyones/cron-crawler:latest
           
      # 推送到阿里云 ACR
      - name: Login to Alibaba Cloud ACR
        uses: docker/login-action@v4
        with:
          registry: crpi-ynz6aj0mqwmi5chm.cn-guangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_ACR_USERNAME }}
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}

      - name: Push image to ACR
        run: |
          docker tag ghcr.io/rickyones/cron-crawler:latest crpi-ynz6aj0mqwmi5chm.cn-guangzhou.personal.cr.aliyuncs.com/rickyone/pdd-cron:latest
          docker push crpi-ynz6aj0mqwmi5chm.cn-guangzhou.personal.cr.aliyuncs.com/rickyone/pdd-cron:latest      